### ISSUE TITLE
[Calendar] Определение даты первого дня

### ISSUE THREAD

**Issue by pavel-b-novikov** [AlinaKapustina/nsudotnet#1]
> DateTime.TryParse("01." + resultDate.Month +"."+ resultDate.Year, out beginMonth)

Это крайне странный способ. Пожалуйста переделайте в человеческий new DateTime(1,...)

**Comment by AlinaKapustina** [comment]
Исправила
 new DateTime(resultDate.Year, resultDate.Month, 1);
