### ISSUE TITLE
[Calendar] Enum.GetValues(typeof(DayOfWeek)

### ISSUE THREAD

**Issue by pavel-b-novikov** [AlinaKapustina/nsudotnet#3]
Похвально, что вы знаете про Enum.GetValues, но пожалуйста найдите другой способ отображать дни недели, при том на русском языке (или на том, который будет выбран в качестве системного).

**Comment by AlinaKapustina** [comment]
Написала с помощью ToString("ddd", CultureInfo.GetCultureInfo("ru-ru"))
