### ISSUE TITLE
[Enigma] Закрытие потоков

### ISSUE THREAD

**Issue by pavel-b-novikov** [AlinaKapustina/nsudotnet#7]
Не все потоки диспозятся. Определите какие и задиспозьте

**Comment by AlinaKapustina** [comment]
Исправила.

А почему за LinesCounter 1балл? она же на 2 балла была

**Comment by pavel-b-novikov** [comment]
Программная ошибка. Не волнуйтесь, уже поправлено, но на гитхабе не показывается.

**Comment by AlinaKapustina** [comment]
Хорошо. А задачу посмотрели?
